### ISSUE TITLE
Error when is executed LDADE_test.py demo() en Python 3.6.1

### ISSUE THREAD

**Issue by clopezno** [amritbhanu/LDADE-package#1]
I am trying execute function demo() and i get the following error

>  \LDADE\DE.py", line 31, in initial_pop
>  dic[self.para_dic.keys()[i]]=self.calls[i]( self.bounds[ i ] )
> TypeError: 'odict_keys' object does not support indexing

Thank you very much,
Carlos López

**Comment by aagrawa8** [comment]
@clopezno This code is currently compatible with only Python2.7.
I haven't tried running it with 3.6.

**Comment by clopezno** [comment]
Thank you for your response.
I tried with Python2.7, and your test ran fine.
